# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build IoT Simulator; compiles for both Windows (x64) and Linux; copies EXE to storage for downloading ease
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEV']
- name: variableGroupName
  default: 'myVariableGroupName'

# ------------------------------------------------------------------------------------------------------------------------
stages:
- stage: BuildSimulator
  displayName: Build Simulator
  jobs:
  - template: templates/console-app-build-template.yml
    parameters:
      variableGroupName: ${{ parameters.variableGroupName }}
      environmentName: 'DEV'

# ----------------------------------------------------------------------------------------------------
- ${{ each environmentName in parameters.environments }} :
  - stage: DeploySimulator${{ environmentName }}
    displayName: Deploy ${{ environmentName }} Simulator
    jobs:
    - template: templates/console-app-deploy-template.yml
      parameters:
        variableGroupName: ${{ parameters.variableGroupName }}
        environmentName: ${{ environmentName }}
